name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: ghcr.io
          name: NikitaRAm/Nest-Top-Page/Nest-Top-Page
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          tags: "develop"